default: build_debug

build_debug: lib/rumcoke/parser.jison lib/rumcoke/translator.rmk
	cp -r lib/ debug/
	jison lib/rumcoke/parser.jison -o debug/rumcoke/parser.js
	./bin/rumcoke lib/rumcoke/translator.rmk > debug/rumcoke/translator.js

accept: build_debug
	node test.js --debug && \
	  cp debug/rumcoke/translator.js lib/rumcoke/translator.js && \
	  echo "// Generated by Jison" > lib/rumcoke/parser.js && \
	  cat debug/rumcoke/parser.js >> lib/rumcoke/parser.js

debug: build_debug
	./bin/rumcoke a.rmk --debug

test: build_debug
	node test.js --debug
