build: lib/rumcoke/_translator.js

lib/rumcoke/_translator.js: lib/rumcoke/translator.js lib/rumcoke/translator.rmk lib/rumcoke/parser.js
	./bin/rumcoke lib/rumcoke/translator.rmk > lib/rumcoke/_translator.js

lib/rumcoke/parser.js: lib/rumcoke/parser.jison
	jison lib/rumcoke/parser.jison -o /tmp/parser.js
	# Add header for github (hide diff)
	echo "// Generated by Jison" > lib/rumcoke/parser.js
	cat /tmp/parser.js >> lib/rumcoke/parser.js

accept: lib/rumcoke/_translator.js
	node test.js --debug && cp lib/rumcoke/_translator.js lib/rumcoke/translator.js

debug: lib/rumcoke/_translator.js
	./bin/rumcoke a.rmk --debug

test: lib/rumcoke/_translator.js
	node test.js --debug
