#!/usr/bin/env node

var util = require("util"),
    fs = require("fs"),
    _ = require("underscore"),
    escodegen = require("escodegen"),
    Parser = require("./parser"),
    Translator = require("./translator");

if(process.argv[2]) {
  if(_.contains(process.argv, "--debug"))
    Translator = require("./_translator");

  exprs = Parser.parser.parse(fs.readFileSync(process.argv[2], "utf8"));
  Translator.translate(exprs);
}
else {
  util.puts("usage: rumcoke foo.rmk > foo.js");
}
